import 'package:flutter/material.dart';
import '../../../core/theme/app_theme.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms of Service')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('BiasGuard Usage Agreement', style: Theme.of(context).textTheme.headlineSmall),
            const SizedBox(height: 24),
            _buildSection(context, '1. Intended Use', 
              'BiasGuard is intended to assist in identifying and mitigating AI bias. It is an advisory platform. Final decision-making authority remains with the user.'),
            _buildSection(context, '2. Ethical Use', 
              'Users agree not to use BiasGuard to circumvent legitimate fairness audits or to promote discriminatory practices.'),
            _buildSection(context, '3. No Warranty', 
              'While we strive for the highest equity scores, the results are generated by AI and should be verified by subject-matter experts.'),
            const SizedBox(height: 32),
            Text('Last updated: April 16, 2026', 
              style: Theme.of(context).textTheme.bodySmall),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(BuildContext context, String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: Theme.of(context).textTheme.titleMedium?.copyWith(color: AppColors.primary)),
          const SizedBox(height: 8),
          Text(content, style: Theme.of(context).textTheme.bodyMedium?.copyWith(height: 1.6)),
        ],
      ),
    );
  }
}
